/**
 * @fileoverview This file defines the main Admin Dashboard page.
 * It serves as the landing page for administrators, providing a high-level
 * overview of system reports and HR activities.
 */
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { UserCheck } from "lucide-react";

/**
 * Renders the main dashboard for administrators.
 * It provides an overview of generated reports and system stats.
 * @returns {JSX.Element} The Admin dashboard page component.
 */
export const metadata = {
  title: "Admin Dashboard",
};


export default function AdminDashboardPage() {
    // In a real application, this data would be fetched from a database.
    const stats = [
        { title: "Pending Approvals", value: "3", icon: <UserCheck />, change: "2 new today" },
    ];
    const recentReports: any[] = [];
    const hrActivities: any[] = [];

  return (
    <div className="space-y-6">
       <div className="flex justify-between items-start">
            <div>
                <h1 className="text-3xl font-bold font-headline">Admin Dashboard</h1>
                <p className="text-muted-foreground">Monitoring system-wide report generation and HR activities.</p>
            </div>
        </div>

        {/* Statistics Cards: A high-level overview of report metrics. */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {stats.length > 0 ? (
                stats.map(stat => (
                    <Card key={stat.title}>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
                            {stat.icon}
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{stat.value}</div>
                            {stat.change && <p className="text-xs text-muted-foreground">{stat.change}</p>}
                        </CardContent>
                    </Card>
                ))
            ) : (
                <p className="text-muted-foreground col-span-4">No statistics available.</p>
            )}
        </div>

        <div className="grid gap-6 md:grid-cols-2">
            {/* Recent Reports Log */}
            <Card>
                <CardHeader>
                    <CardTitle>Recent Report Activity</CardTitle>
                    <CardDescription>A log of the latest reports generated by HR personnel.</CardDescription>
                </CardHeader>
                <CardContent>
                    {recentReports.length > 0 ? (
                        <>
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead>Report ID</TableHead>
                                        <TableHead>Report Type</TableHead>
                                        <TableHead>Generated By</TableHead>
                                        <TableHead className="text-right">Status</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {recentReports.map(report => (
                                        <TableRow key={report.id}>
                                            <TableCell className="font-mono text-xs">
                                              <Link href={`/admin/reports/${report.id}`} className="hover:underline text-primary">
                                                {report.id}
                                              </Link>
                                            </TableCell>
                                            <TableCell>{report.type}</TableCell>
                                            <TableCell>{report.generatedBy}</TableCell>
                                            <TableCell className="text-right">
                                                <Badge variant={report.status === 'Success' ? 'default' : 'destructive'} className={report.status === 'Success' ? 'bg-green-500' : ''}>
                                                    {report.status}
                                                </Badge>
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                             <div className="flex justify-end pt-4 -mb-4">
                                <Button asChild variant="link">
                                    <Link href="/admin/reports">View All Reports</Link>
                                </Button>
                            </div>
                        </>
                    ) : (
                        <p className="text-muted-foreground text-center">No recent reports.</p>
                    )}
                </CardContent>
            </Card>
             {/* Recent HR Activity Log */}
            <Card>
                <CardHeader>
                    <CardTitle>Recent HR Activity</CardTitle>
                    <CardDescription>A log of recent actions taken by HR personnel.</CardDescription>
                </CardHeader>
                <CardContent>
                     {hrActivities.length > 0 ? (
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Activity</TableHead>
                                    <TableHead>HR Personnel</TableHead>
                                    <TableHead className="text-right">Timestamp</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {hrActivities.map(activity => (
                                    <TableRow key={activity.id}>
                                        <TableCell className="font-medium flex items-center gap-2">
                                            <Badge variant="outline" className="text-xs">{activity.type}</Badge>
                                            <span>{activity.activity}</span>
                                        </TableCell>
                                        <TableCell>{activity.user}</TableCell>
                                        <TableCell className="text-right text-muted-foreground text-xs">{activity.timestamp}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    ) : (
                        <p className="text-muted-foreground text-center">No recent HR activity.</p>
                    )}
                </CardContent>
            </Card>
        </div>
    </div>
  );
}
